---
- name: Select Control-M Jobs with Wildcard Filtering
  hosts: controlm_server
  tasks:
    - name: Get Access Token
      uri:
        url: "https://your-controlm-server/automation-api/token"
        method: POST
        body_format: json
        body:
          username: your_username
          password: your_password
      register: access_token

    - name: Get Jobs
      uri:
        url: "https://your-controlm-server/automation-api/jobs"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token.json.access_token }}"
      register: jobs_output

    - name: Filter Jobs
      set_fact:
        selected_jobs: "{{ jobs_output.json | json_query(query) }}"
      vars:
        query: "[?contains(jobName, '{{ job_name_pattern }}') || contains(otherAttribute, '{{ other_attribute_pattern }}')]"

    - name: Print Jobs
      debug:
        var: item
      loop: "{{ selected_jobs }}"
