---
- name: Download artifact from Artifactory
  get_url:
    url: "{{ artifact_url }}"
    dest: "/tmp/{{ web.artifact_name }}"
    mode: '0440'

- name: Extract artifact
  unarchive:
    src: "/tmp/{{ web.artifact_name }}"
    dest: "/tmp"
    remote_src: yes

- name: Copy files to target folder
  command:
    cmd: "cp -r /tmp/{{ web.root_path }} {{ target_folder }}"

- name: Run the script
  command: "{{ web.script_path }}"
